// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/doctorpb/doctor.proto

package doctorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Doctor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Specialization string                 `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_proto_doctorpb_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *Doctor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Doctor) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Doctor) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *Doctor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateDoctorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FullName       string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Specialization string                 `protobuf:"bytes,2,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDoctorRequest) Reset() {
	*x = CreateDoctorRequest{}
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoctorRequest) ProtoMessage() {}

func (x *CreateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoctorRequest.ProtoReflect.Descriptor instead.
func (*CreateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctorpb_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDoctorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateDoctorRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *CreateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorRequest) Reset() {
	*x = GetDoctorRequest{}
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorRequest) ProtoMessage() {}

func (x *GetDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctorpb_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *GetDoctorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDoctorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsRequest) Reset() {
	*x = ListDoctorsRequest{}
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsRequest) ProtoMessage() {}

func (x *ListDoctorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsRequest.ProtoReflect.Descriptor instead.
func (*ListDoctorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctorpb_doctor_proto_rawDescGZIP(), []int{3}
}

type DoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctor        *Doctor                `protobuf:"bytes,1,opt,name=doctor,proto3" json:"doctor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctorpb_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *DoctorResponse) GetDoctor() *Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

type ListDoctorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctors       []*Doctor              `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsResponse) Reset() {
	*x = ListDoctorsResponse{}
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsResponse) ProtoMessage() {}

func (x *ListDoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctorpb_doctor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsResponse.ProtoReflect.Descriptor instead.
func (*ListDoctorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctorpb_doctor_proto_rawDescGZIP(), []int{5}
}

func (x *ListDoctorsResponse) GetDoctors() []*Doctor {
	if x != nil {
		return x.Doctors
	}
	return nil
}

var File_proto_doctorpb_doctor_proto protoreflect.FileDescriptor

const file_proto_doctorpb_doctor_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/doctorpb/doctor.proto\x12\tdoctor.v1\"s\n" +
	"\x06Doctor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12&\n" +
	"\x0especialization\x18\x03 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"p\n" +
	"\x13CreateDoctorRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12&\n" +
	"\x0especialization\x18\x02 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\"\n" +
	"\x10GetDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ListDoctorsRequest\";\n" +
	"\x0eDoctorResponse\x12)\n" +
	"\x06doctor\x18\x01 \x01(\v2\x11.doctor.v1.DoctorR\x06doctor\"B\n" +
	"\x13ListDoctorsResponse\x12+\n" +
	"\adoctors\x18\x01 \x03(\v2\x11.doctor.v1.DoctorR\adoctors2\xed\x01\n" +
	"\rDoctorService\x12I\n" +
	"\fCreateDoctor\x12\x1e.doctor.v1.CreateDoctorRequest\x1a\x19.doctor.v1.DoctorResponse\x12C\n" +
	"\tGetDoctor\x12\x1b.doctor.v1.GetDoctorRequest\x1a\x19.doctor.v1.DoctorResponse\x12L\n" +
	"\vListDoctors\x12\x1d.doctor.v1.ListDoctorsRequest\x1a\x1e.doctor.v1.ListDoctorsResponseB(Z&doctor-service/proto/doctorpb;doctorpbb\x06proto3"

var (
	file_proto_doctorpb_doctor_proto_rawDescOnce sync.Once
	file_proto_doctorpb_doctor_proto_rawDescData []byte
)

func file_proto_doctorpb_doctor_proto_rawDescGZIP() []byte {
	file_proto_doctorpb_doctor_proto_rawDescOnce.Do(func() {
		file_proto_doctorpb_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_doctorpb_doctor_proto_rawDesc), len(file_proto_doctorpb_doctor_proto_rawDesc)))
	})
	return file_proto_doctorpb_doctor_proto_rawDescData
}

var file_proto_doctorpb_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_doctorpb_doctor_proto_goTypes = []any{
	(*Doctor)(nil),              // 0: doctor.v1.Doctor
	(*CreateDoctorRequest)(nil), // 1: doctor.v1.CreateDoctorRequest
	(*GetDoctorRequest)(nil),    // 2: doctor.v1.GetDoctorRequest
	(*ListDoctorsRequest)(nil),  // 3: doctor.v1.ListDoctorsRequest
	(*DoctorResponse)(nil),      // 4: doctor.v1.DoctorResponse
	(*ListDoctorsResponse)(nil), // 5: doctor.v1.ListDoctorsResponse
}
var file_proto_doctorpb_doctor_proto_depIdxs = []int32{
	0, // 0: doctor.v1.DoctorResponse.doctor:type_name -> doctor.v1.Doctor
	0, // 1: doctor.v1.ListDoctorsResponse.doctors:type_name -> doctor.v1.Doctor
	1, // 2: doctor.v1.DoctorService.CreateDoctor:input_type -> doctor.v1.CreateDoctorRequest
	2, // 3: doctor.v1.DoctorService.GetDoctor:input_type -> doctor.v1.GetDoctorRequest
	3, // 4: doctor.v1.DoctorService.ListDoctors:input_type -> doctor.v1.ListDoctorsRequest
	4, // 5: doctor.v1.DoctorService.CreateDoctor:output_type -> doctor.v1.DoctorResponse
	4, // 6: doctor.v1.DoctorService.GetDoctor:output_type -> doctor.v1.DoctorResponse
	5, // 7: doctor.v1.DoctorService.ListDoctors:output_type -> doctor.v1.ListDoctorsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_doctorpb_doctor_proto_init() }
func file_proto_doctorpb_doctor_proto_init() {
	if File_proto_doctorpb_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_doctorpb_doctor_proto_rawDesc), len(file_proto_doctorpb_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_doctorpb_doctor_proto_goTypes,
		DependencyIndexes: file_proto_doctorpb_doctor_proto_depIdxs,
		MessageInfos:      file_proto_doctorpb_doctor_proto_msgTypes,
	}.Build()
	File_proto_doctorpb_doctor_proto = out.File
	file_proto_doctorpb_doctor_proto_goTypes = nil
	file_proto_doctorpb_doctor_proto_depIdxs = nil
}
