// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/appointmentpb/appointment.proto

package appointmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DoctorId      string                 `protobuf:"bytes,4,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Appointment) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateAppointmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentStatusRequest) Reset() {
	*x = UpdateAppointmentStatusRequest{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentStatusRequest) ProtoMessage() {}

func (x *UpdateAppointmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAppointmentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAppointmentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *ListAppointmentsRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type AppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentResponse) Reset() {
	*x = AppointmentResponse{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentResponse) ProtoMessage() {}

func (x *AppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentResponse.ProtoReflect.Descriptor instead.
func (*AppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *AppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointmentpb_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointmentpb_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

var File_proto_appointmentpb_appointment_proto protoreflect.FileDescriptor

const file_proto_appointmentpb_appointment_proto_rawDesc = "" +
	"\n" +
	"%proto/appointmentpb/appointment.proto\x12\x0eappointment.v1\"\x8a\x01\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoctor_id\x18\x04 \x01(\tR\bdoctorId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"o\n" +
	"\x18CreateAppointmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x1eUpdateAppointmentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x17ListAppointmentsRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\"T\n" +
	"\x13AppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"[\n" +
	"\x18ListAppointmentsResponse\x12?\n" +
	"\fappointments\x18\x01 \x03(\v2\x1b.appointment.v1.AppointmentR\fappointments2\xad\x03\n" +
	"\x12AppointmentService\x12b\n" +
	"\x11CreateAppointment\x12(.appointment.v1.CreateAppointmentRequest\x1a#.appointment.v1.AppointmentResponse\x12\\\n" +
	"\x0eGetAppointment\x12%.appointment.v1.GetAppointmentRequest\x1a#.appointment.v1.AppointmentResponse\x12n\n" +
	"\x17UpdateAppointmentStatus\x12..appointment.v1.UpdateAppointmentStatusRequest\x1a#.appointment.v1.AppointmentResponse\x12e\n" +
	"\x10ListAppointments\x12'.appointment.v1.ListAppointmentsRequest\x1a(.appointment.v1.ListAppointmentsResponseB7Z5appointment-service/proto/appointmentpb;appointmentpbb\x06proto3"

var (
	file_proto_appointmentpb_appointment_proto_rawDescOnce sync.Once
	file_proto_appointmentpb_appointment_proto_rawDescData []byte
)

func file_proto_appointmentpb_appointment_proto_rawDescGZIP() []byte {
	file_proto_appointmentpb_appointment_proto_rawDescOnce.Do(func() {
		file_proto_appointmentpb_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointmentpb_appointment_proto_rawDesc), len(file_proto_appointmentpb_appointment_proto_rawDesc)))
	})
	return file_proto_appointmentpb_appointment_proto_rawDescData
}

var file_proto_appointmentpb_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_appointmentpb_appointment_proto_goTypes = []any{
	(*Appointment)(nil),                    // 0: appointment.v1.Appointment
	(*CreateAppointmentRequest)(nil),       // 1: appointment.v1.CreateAppointmentRequest
	(*GetAppointmentRequest)(nil),          // 2: appointment.v1.GetAppointmentRequest
	(*UpdateAppointmentStatusRequest)(nil), // 3: appointment.v1.UpdateAppointmentStatusRequest
	(*ListAppointmentsRequest)(nil),        // 4: appointment.v1.ListAppointmentsRequest
	(*AppointmentResponse)(nil),            // 5: appointment.v1.AppointmentResponse
	(*ListAppointmentsResponse)(nil),       // 6: appointment.v1.ListAppointmentsResponse
}
var file_proto_appointmentpb_appointment_proto_depIdxs = []int32{
	0, // 0: appointment.v1.AppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	0, // 1: appointment.v1.ListAppointmentsResponse.appointments:type_name -> appointment.v1.Appointment
	1, // 2: appointment.v1.AppointmentService.CreateAppointment:input_type -> appointment.v1.CreateAppointmentRequest
	2, // 3: appointment.v1.AppointmentService.GetAppointment:input_type -> appointment.v1.GetAppointmentRequest
	3, // 4: appointment.v1.AppointmentService.UpdateAppointmentStatus:input_type -> appointment.v1.UpdateAppointmentStatusRequest
	4, // 5: appointment.v1.AppointmentService.ListAppointments:input_type -> appointment.v1.ListAppointmentsRequest
	5, // 6: appointment.v1.AppointmentService.CreateAppointment:output_type -> appointment.v1.AppointmentResponse
	5, // 7: appointment.v1.AppointmentService.GetAppointment:output_type -> appointment.v1.AppointmentResponse
	5, // 8: appointment.v1.AppointmentService.UpdateAppointmentStatus:output_type -> appointment.v1.AppointmentResponse
	6, // 9: appointment.v1.AppointmentService.ListAppointments:output_type -> appointment.v1.ListAppointmentsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_appointmentpb_appointment_proto_init() }
func file_proto_appointmentpb_appointment_proto_init() {
	if File_proto_appointmentpb_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointmentpb_appointment_proto_rawDesc), len(file_proto_appointmentpb_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointmentpb_appointment_proto_goTypes,
		DependencyIndexes: file_proto_appointmentpb_appointment_proto_depIdxs,
		MessageInfos:      file_proto_appointmentpb_appointment_proto_msgTypes,
	}.Build()
	File_proto_appointmentpb_appointment_proto = out.File
	file_proto_appointmentpb_appointment_proto_goTypes = nil
	file_proto_appointmentpb_appointment_proto_depIdxs = nil
}
